services:
  espublico.kata.orders:
    image: espublico.kata.orders
    build:
      context: .
      dockerfile: EsPublico.Kata.Orders/Dockerfile
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: espublico
      POSTGRES_PASSWORD: espublico
      POSTGRES_DB: espublico
    ports:
      - "5432:5432"